theme: jekyll-theme-prologue
collections: [sections]
remote_theme: chrisbobbe/jekyll-theme-prologue

title: Cignex Datamatics
subtitle: Technical Trainings
author: Vishal Rangras
email: vishal.rangras@cignex.com
github_url: https://github.com/cignextraining
facebook_url: https://www.facebook.com/CIGNEXTechnologies/
linkedin_url: https://www.linkedin.com/company/cignex-datamatics

show_downloads: "true"

permalink: pretty
avatar: ./imgs/Logo_400x400.GIF

markdown: kramdown

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'